stages:
  - build
  - publish
  - deploy

variables:
  DOCKER_IMAGE: "$DOCKER_REGISTRY/dulno-proxy"

build:
  stage: build
  image: gradle:8.12-jdk21
  script:
    - gradle bootJar
  artifacts:
    paths:
      - build/libs/
    expire_in: 1 day

publish:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  dependencies:
    - build
  script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_REGISTRY
    - docker build -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:latest
  only:
    - master

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBERNETES_CONFIGURATION" > ~/.kube/config
  script:
    - kubectl rollout restart deployment/dulno-proxy-deployment
  only:
    - master
